title: לא מדויק
email: gadial@gmail.com
description: >- 
  בלוג על מתמטיקה ומדעי המחשב
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: לא-מדויק-163347110378474
facebook_linkame: "לא מדויק"
permalink: /:year/:month/:day/:title
disqus:
  shortname: "not-precise"
post_images: /assets/img
environment: production
# Build settings
markdown: kramdown
kramdown:
  parse_span_html: false
  parse_block_html: false
theme: minima
plugins:
  - jekyll-feed

collections:
  categories:
    output: true
  tags:
    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - docs
  - Notebooks
  - node_modules
  - raw_posts
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
